CREATE TABLE IF NOT EXISTS votes
(
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code      text    NOT NULL,
    vote_number_before integer NOT NULL,
    voter              text    NOT NULL,
    choice             text    NOT NULL,
    status             bool    NOT NULL,
    created_at_unix    integer NOT NULL
);

CREATE INDEX IF NOT EXISTS votes_campaign_code_created_at_idx
    ON votes (campaign_code, created_at_unix DESC);
