import { closePool, query } from '../config/db.js';

const schemaSql = `
  DROP TABLE IF EXISTS votes CASCADE;

  CREATE TABLE IF NOT EXISTS votes
  (
      id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      campaign_code      text    NOT NULL,
      vote_number_before integer NOT NULL,
      voter              text    NOT NULL,
      choice             text    NOT NULL,
      status             bool    NOT NULL,
      created_at_unix    integer NOT NULL
  );
`;

try {
  await query(schemaSql);
  console.log('Database schema initialized');
} catch (error) {
  console.error('Database schema initialization failed');
  console.error(error.message || error.code || error);
  process.exitCode = 1;
} finally {
  await closePool();
}
